insert into user_details(id, birth_date, name)
values (1001, current_date(), 'Rafal')
insert into user_details(id, birth_date, name)
values (1002, current_date(), 'Naru')
insert into user_details(id, birth_date, name)
values (1003, current_date(), 'Jennie')
